### PR TITLE
Update native-lib.cpp

### PR DESCRIPTION
**Pull request by george521**
Liar...

### CODE REVIEW

**Comment by chrisk44** [comment]
What AVL? Why did you... what are you trying to.... what??

**Comment by george521** [comment]
The description had something about AVL and i couldn't find anything relevant with it...

**Comment by chrisk44** [comment]
Description?

**Comment by george521** [comment]
The description on the last commited change

**Comment by chrisk44** [comment]
AVL was changed to HashMap [here](https://github.com/chrisk44/Hijacker/commit/004cdfb378a4d05370d8e26a1a67290dee36f346)...
Aplhroforhtoi malakes...

**Comment by george521** [comment]
We are talking about cpp not java

**Pull request closed without merging**
